### PR TITLE
Update to v5.1.0

### PR DESCRIPTION
**Pull request by daniestevez**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by daniestevez** [comment]
@conda-forge-admin, please rerender

**Comment by ryanvolz** [comment]
The problem appears to be missing symbols related to `fmt`, although it's a mystery that we're just hitting this now? AFAICT gr-satellites doesn't do anything with `fmt` other than what comes from being a GR OOT module, so to properly fix this will probably involve the `gnuradio` package. As a guess, there's probably a workaround by just adding `fmt` as a host dependency and re-rendering.

**Comment by ryanvolz** [comment]
I think the `spdlog` package is what broke this actually. Haven't dug into it yet, but there was a new one built 3 days ago and now a PR for fixing external `fmt` support: https://github.com/conda-forge/spdlog-feedstock/pull/51.

**Comment by ryanvolz** [comment]
So I think `gnuradio` does need to be rebuilt now with the new `spdlog` package that broke ABI compatibility. I'm holding off on just doing that for the moment because I also think that a further change is needed to `spdlog` so that it tells everything compiling against it that they now need to depend on the separate external `fmt` package. We'll see what those maintainers say about how to move forward.

**Comment by daniestevez** [comment]
Awesome. This is building correctly now. I'll go ahead and merge it.

**Pull request merged**
